# Generated by Django 2.0.10 on 2020-05-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_youtubevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-update']},
        ),
    ]
